### ISSUE TITLE
Reason for bitwarden deprecation

### ISSUE THREAD

**Issue by crocuda** [PierreBeucher/novops#60]
Why have you choose to deprecate bitwarden?
I don't use it myself.
 I just wanted to know the motivations behind this choice.

**Comment by PierreBeucher** [comment]
Good question. In short because BitWarden was a pain to use and integrate. 

Long answer: we rely on direct call to BitWarden `bw` CLI, which needs a `BW_SESSION` environment variable for authentication. However BitWarden CLI proved buggy and limited: different versions or same version installed with different tools (say apt or snap) yielded different behaviours, causing lots of bugs. I was working at Novadiscovery in that time and we were using BitWarden internally to store our secrets, we've long changed secret provider since.

I'd like to use a REST API instead of CLI but BitWarden doesn't provide access to secrets via API (see https://bitwarden.com/help/api/) - or at least doesn't document it. 

This was some time ago though, maybe things changed since. 

BTW where did you find deprecation notice? There's a small comment in code mentioning a potential deprecation, but nothing more I'm aware of

**Comment by PierreBeucher** [comment]
BTW where did you find deprecation notice? There's a small comment in code mentioning a potential deprecation, but nothing more I'm aware or

**Comment by crocuda** [comment]
Okay! That tells a lot of things on Bitwarden software stability.
I encountered the said comment in the source code and may have read a little bit too fast and thought deprecation was eventually already scheduled.
