### ISSUE TITLE
list the environments in the same order as in the .yaml

### ISSUE THREAD

**Issue by teto** [PierreBeucher/novops#63]
We have in our .yaml file the environments listed as dev/dev-bis/... but novops displays them in seemingly arbitrary order:
`Select environment: dev-bis, prod, preprod, backup-account-dev, backup-account-restore, backup-account-staging, backup-account-preprod, backup-account-prod, backup-account-qa, qa, restore, dev, staging (default: dev)`

I wish their display could be the same as in the yaml file (to put harmless environments at the beginning for instance)

**Comment by PierreBeucher** [comment]
Ah indeed, env selection is not friendly when lots of environments are available.

I was thinking of a more interactive way, such as having a list with numbers (you can then press a number) and/or a dropdown list from which arrow keys can be used to navigate in and pressing enter rather than entering environment name by hand.

Listing environment in the order they appear can be a first quick win

**Comment by teto** [comment]
I think the improved prompt could be solved via https://github.com/PierreBeucher/novops/issues/61 so anyone can implement its selection system, fzf is perfect for that IMO.

**Comment by PierreBeucher** [comment]
Indeed, solved by https://github.com/PierreBeucher/novops/pull/79 along with #61.

Well, not exactly by listing in the same order as YAML, but just listing as an ordered list, which should answer this use case by simply adding "zz-" or having numbers as env name prefix like "1. dev"
