### ISSUE TITLE
ZSH: arrow are not correctly bound on load

### ISSUE THREAD

**Issue by Neferites** [PierreBeucher/novops#91]
**Describe the bug**
When `source <(novops load)` is run on `zsh` with multiples env (dev / int), environment can't be selected with arrows.

**To Reproduce**
1. Run `apt install -y zsh`
2. Run `zsh`
3. Run `source <(novops load)`
4. try to select an env

**Expected behavior**
Env should be selected using arrows.

**Environment:**
* Novops Version: 0.11.0
* ZSH Version:  zsh 5.8 (x86_64-debian-linux-gnu)
* Server Operating System/Architecture: Debian 11.8 / WSL Ubuntu 22.04

**Additional context**
N/A.

**Comment by PierreBeucher** [comment]
Thanks for the report, I'll be right on it

**Comment by PierreBeucher** [comment]
Got some progress on this. In `zsh` you can use `=(novops load)` instead of `<(novops load)` (`=()` is a [`zsh` specific syntax for process substitution](https://linux.die.net/man/1/zshexpn))

In `zsh` the `<()` documented different is that sub-process result is written to a pipe instead of a temporary file, but it does not say anything about how a process attaches to terminal's stdin. Still enquiring.

**Comment by PierreBeucher** [comment]
Added doc for zsh / ksh for which `=()` is preferred over `<()` https://novops.dev/examples/shell.html
